### ISSUE TITLE
Organization of types

### ISSUE THREAD

**Issue by szattila98** [szattila98/veryrezsi#10]
Types should be organized into a `types` directory in src root, from whence they would be imported.
The folder structure in types should resemble the directory structure of `routes`, with files for every page's types.

In the future there might be individual components that are not routes, those might need types, so maybe the `types`directory should contain a `routes` and a `components` directory. @djavorek Whatcha think?

**Comment by djavorek** [comment]
I have added a `shared` dir for types in my current PR (#18)
We can rename it to types, but this was the convention what I found somewhere so I went with this.

**Comment by szattila98** [comment]
I am resolving this request in #28 . There will be an `api` directory in shared where in separate files the api requests, responses, data types will be placed.
