### ISSUE TITLE
btoa error on node 14

### ISSUE THREAD

**Issue by szattila98** [szattila98/veryrezsi#13]
When trying to develop with Node 14, login shows this error.

![image](https://user-images.githubusercontent.com/37137309/161445314-9bc56638-1d55-4916-bfc5-2bb2bf2131cb.png)

I read somewhere that btoa is being deprecated, maybe the effect of that is this.
Or maybe the app should not even run on Node 14? If so somewhere in the readme we should specify.

**Comment by djavorek** [comment]
Will look into this, btoa was a quick decision only.

**Comment by szattila98** [comment]
But changing to Node-16 solved it so it's not critical, as we already only have the CI set on Node-16, we could just say that that is required and end of story. I will let you be the judge of that.
