### ISSUE TITLE
JSDoc typings into their own place 

### ISSUE THREAD

**Issue by djavorek** [szattila98/veryrezsi#33]
> I think we should root out these jsdoc typings, they look look wrong, idk why.
This [link](https://vitejs.dev/config/#config-intellisense) should help in this case, but this comment can be made into it's own separate issue, what do you think about all this?

Stop using ugly jsdoc type descriptions, that are there just for intellisense.

**Comment by szattila98** [comment]
With a new project bootstrapped, we can use the typescript typings instead of the jsdocs. On the svelte doc page, there is a switch for it too, so we can copy relevant typescript typings and not jsdoc typings.
