### ISSUE TITLE
Consider adding VeryRezsi to SeaORM showcase!

### ISSUE THREAD

**Issue by billy1624** [szattila98/veryrezsi#34]
Hey @szattila98, feel free to submit a PR to showcase your project!
- https://github.com/SeaQL/sea-orm/issues/403

**Comment by djavorek** [comment]
@szattila98, if you think it is a good idea, I have created a draft PR for this:

https://github.com/SeaQL/sea-orm/pull/858/files

**Comment by szattila98** [comment]
Sure, there you go :smile:

**Comment by billy1624** [comment]
THanks! @djavorek @szattila98
