### ISSUE TITLE
SvelteKit update - Code migration

### ISSUE THREAD

**Issue by djavorek** [szattila98/veryrezsi#38]
Updating to the latest version of SvelteKit requires some code changes. (Even _npm i_ will fail otherwise)

See https://github.com/sveltejs/kit/discussions/5774, for the required changes

**Comment by djavorek** [comment]
**So do NOT try to delete package-lock.json, because you will face the following error.**

![image](https://user-images.githubusercontent.com/35934971/184967253-049d702e-a8a2-408f-8e56-361566bf5ee6.png)

**Comment by szattila98** [comment]
But... why?

**Comment by szattila98** [comment]
We will bootstrap a completely new project, as migration is too much of a pain, considering that SMUI will be eradicated, but migrating the old project would also require migrating that weirdness.
