### ISSUE TITLE
Use userid path variable for the implementation of /api/expense/:userid 

### ISSUE THREAD

**Issue by djavorek** [szattila98/veryrezsi#42]
## Problem

I just realized, I used the AuthenticatedUser object to get the user id, instead of the path variable.
It does not matter much **as for now authenticated users should only be able to access their own expenses.**
However it can change in the future and we can also avoid later confusion this way.

## Solution
Use _Path(userid)_ and check it against the userid coming from _AuthenticatedUser_ object.
Return 403 (Forbidden) if those differ.

**Comment by szattila98** [comment]
Yeah, it makes sense from a future-proofing standpoint.
