### ISSUE TITLE
Implementing user profile page

### ISSUE THREAD

**Issue by szattila98** [szattila98/veryrezsi#5]
The page should contain information like, username, password and e-mail.
Other settings-like functionalities should be here in the future like credential changes, and other account management stuff.

**Comment by djavorek** [comment]
This githead autoclosed this issue. 🔫
It needs another PR to be completed, I just finished authentication, user profile page needs more work.

**Comment by djavorek** [comment]
Merged https://github.com/szattila98/veryrezsi/pull/18
