### ISSUE TITLE
Configure docker cache in actions

### ISSUE THREAD

**Issue by szattila98** [szattila98/veryrezsi#70]
Our actions which use docker should use jobs provided by the Docker team. This would be good because like this we can take advantage of its caching, and our build and publishing pipeline would run much quicker. Refer to the links for more info.

https://docs.docker.com/build/cache/backends/gha/
https://depot.dev/blog/docker-layer-caching-in-github-actions

**Comment by djavorek** [comment]
This was done in #63 for Server Docker build (which takes the most time). It helps a bit if there is no server change.
See: https://github.com/szattila98/veryrezsi/blob/main/.github/workflows/images.yml#L74-L80

If it needs to be implemented for something else, then we should consider our GH actions quote.
