### ISSUE TITLE
The client side cannot fully interact with the backend because of CSRF limitations

### ISSUE THREAD

**Issue by szattila98** [szattila98/veryrezsi#77]
I wanted to view your work so I started up everything in docker and I saw this when I wanted to login.
![image](https://github.com/szattila98/veryrezsi/assets/37137309/b222cf92-637d-43cf-b309-71b9adc39b8c)
Locally it works fine, I will be opening an issue to resolve this.

The design looks so cool! 🤩

_Originally posted by @szattila98 in https://github.com/szattila98/veryrezsi/issues/72#issuecomment-1584060537_

**Comment by djavorek** [comment]
https://github.com/szattila98/veryrezsi/pull/79
